=== michzimm/redfish_simgen/hp_server.template/redfish/v1/schemastore/en/Session.json/index.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "@odata.id": "Session",
    "additionalProperties": false,
    "copyright": "Copyright 2014-2019 Hewlett Packard Enterprise Development, LP.  Portions Copyright 2014-2019 Distributed Management Task Force. All rights reserved.",
    "description": "The Session resource describes a single connection (session) between a client and a Redfish service instance.",
    "properties": {
        "@odata.context": {
            "$ref": "Resource.json#/definitions/odatacontext"
        },
        "@odata.etag": {
            "$ref": "Resource.json#/definitions/odataetag"
        },
        "@odata.id": {
            "$ref": "Resource.json#/definitions/odataid"
        },
        "@odata.type": {
            "$ref": "Resource.json#/definitions/odatatype"
        },
        "Description": {
            "$ref": "Resource.json#/definitions/Description"
        },
        "Id": {
            "$ref": "Resource.json#/definitions/Id"
        },
        "Name": {
            "$ref": "Resource.json#/definitions/Name"
        },
        "Oem": {
            "additionalProperties": true,
            "properties": {
                "Hpe": {
                    "$ref": "HpeiLOSession.json#"
                }
            },
            "type": "object"
        },
        "UserName": {
            "description": "Name to use to log in to the management processor.",
            "etag": true,
            "readonly": true,
            "type": "string"
        }
    },
    "readonly": true,
    "title": "#Session.v1_0_0.Session",
    "type": "object"
}

=== michzimm/redfish_simgen/hp_server.template/redfish/v1/CertificateService/CertificateLocations/index.json
{
    "@odata.context": "/redfish/v1/$metadata#CertificateLocations.CertificateLocations",
    "@odata.etag": "W/\"A3A6BF43\"",
    "@odata.id": "/redfish/v1/CertificateService/CertificateLocations",
    "@odata.type": "#CertificateLocations.v1_0_2.CertificateLocations",
    "Id": "CertificateLocations",
    "Description": "Certificate Locations",
    "Name": "Certificate Locations"
}

=== michzimm/redfish_simgen/hp_server.template/redfish/v1/SessionService/Sessions/administrator0000000062eaac156dd5bac6/index.json
{
    "@odata.context": "/redfish/v1/$metadata#Session.Session",
    "@odata.etag": "W/\"B4B2DE04\"",
    "@odata.id": "/redfish/v1/SessionService/Sessions/administrator0000000062eaac156dd5bac6",
    "@odata.type": "#Session.v1_0_0.Session",
    "Id": "administrator0000000062eaac156dd5bac6",
    "Description": "Manager User Session",
    "Name": "User Session",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeiLOSession.HpeiLOSession",
            "@odata.type": "#HpeiLOSession.v2_1_0.HpeiLOSession",
            "AccessTime": "2022-08-03T17:14:21Z",
            "LoginTime": "2022-08-03T17:10:45Z",
            "MySession": false,
            "UserExpires": "2022-08-03T17:44:21Z",
            "UserIP": "10.117.20.71",
            "UserTag": "Web UI",
            "UserType": "Local"
        }
    },
    "UserName": "Administrator"
}

=== michzimm/redfish_simgen/hp_server.template/redfish/v1/SessionService/Sessions/engineer0000000062eaa97ac875793d/index.json
{
    "@odata.context": "/redfish/v1/$metadata#Session.Session",
    "@odata.etag": "W/\"0258FCFE\"",
    "@odata.id": "/redfish/v1/SessionService/Sessions/engineer0000000062eaa97ac875793d",
    "@odata.type": "#Session.v1_0_0.Session",
    "Id": "engineer0000000062eaa97ac875793d",
    "Description": "Manager User Session",
    "Name": "User Session",
    "Oem": {
        "Hpe": {
            "@odata.context": "/redfish/v1/$metadata#HpeiLOSession.HpeiLOSession",
            "@odata.type": "#HpeiLOSession.v2_1_0.HpeiLOSession",
            "AccessTime": "2022-08-03T17:13:37Z",
            "LoginTime": "2022-08-03T16:59:38Z",
            "MySession": false,
            "UserExpires": "2022-08-03T17:43:37Z",
            "UserIP": "10.105.219.160",
            "UserTag": "REST",
            "UserType": "Local"
        }
    },
    "UserName": "engineer"
}
